#' @title get_responses
#' 
#' @description Get responses for a SurveyMonkey survey
#' 
#' @param survey A sm_survey object, as retrieved by \code{surveylist()}.
#' @param collector A sm_collector object, as retrieved by \code{collectorlist}. By default = NULL
#' @param bulk A logical variable to indicate if list response should include a list of full expanded responses, including answers to all questions. By default = FALSE
#' @param page Integer number to select which page of resources to return. By default is 1.
#' @param all_pages All pages?
#' @param per_page Integer number to set the number of surveys to return per page. By default, is 50 surveys per page.
#' @param start_created_at Date string used to select surveys created after this date. By default is NULL.
#' @param end_created_at Date string used to select surveys modified before this date. By default is NULL.
#' @param start_modified_at Date string used to select surveys last modified after this date. By default is NULL.
#' @param end_modified_at Date string used to select surveys modified before this date. By default is NULL.
#' @param sort_order String used to set the sort order for returned surveys: 'ASC' or 'DESC'. By default, DESC.
#' @param sort_by String value of field used to sort returned survey list: 'title', 'date_modified', or 'num_response'. By default, date_modified.
#' @param oauth_token Your OAuth 2.0 token, as generated by \code{smlogin}. By default, retrieved from \code{getOption('sm_oauth_token')}.
#' @param ... Other arguments for httr::GET
#' 
#' @return A list of object of class {sm_response}
#' 
#' @references SurveyMonkey API V3 at \url{https://developer.surveymonkey.com/api/v3/#survey-responses}
#' 
#' @export

get_responses <- function(survey,
                          collector = NULL,
                          bulk = FALSE,
                          page = 1,
                          all_pages = FALSE,
                          per_page = NULL,
                          start_created_at = NULL,
                          end_created_at = NULL,
                          start_modified_at = NULL,
                          end_modified_at = NULL,
                          sort_order = 'DESC',
                          sort_by = 'date_modified',
                          oauth_token = getOption('sm_oauth_token'),
                          ...) {
  if (inherits(survey, 'sm_survey')) {
    survey$id <- survey$id
  } else {
    stop("'survey' is not of class sm_survey")
  }
  
  if (!is.null(collector)) {
    if (bulk) {
      u <- paste('https://api.surveymonkey.net/v3/collectors/', collector$id,'/responses/bulk?', sep = '')   
    } else {
      u <- paste('https://api.surveymonkey.net/v3/collectors/', collector$id,'/responses?', sep = '')  
    }
  } else {
    if (bulk) {
      u <- paste('https://api.surveymonkey.net/v3/surveys/', survey$id,'/responses/bulk?', sep = '')  
    } else {
      u <- paste('https://api.surveymonkey.net/v3/surveys/', survey$id,'/responses?', sep = '')  
    }
  }
  
  if (!is.null(oauth_token)) {
    token <- paste('bearer', oauth_token)
  } else {
    stop("Must specify 'oauth_token', Try using smlogin() first.")
  }
  
  if (inherits(start_created_at, "POSIXct") | inherits(start_created_at, "Date")) {
    start_created_at <- format(start_created_at, "%Y-%m-%d %H:%M:%S", tz = "UTC")
  }
  
  if (inherits(end_created_at, "POSIXct") | inherits(end_created_at, "Date")) {
    end_created_at <- format(end_created_at, "%Y-%m-%d %H:%M:%S", tz = "UTC")
  }
  
  if (inherits(start_modified_at, "POSIXct") | inherits(start_modified_at, "Date")) {
    start_modified_at <- format(start_modified_at, "%Y-%m-%d %H:%M:%S", tz = "UTC")
  }
  
  if (inherits(end_modified_at, "POSIXct") | inherits(end_modified_at, "Date")) {
    end_modified_at <- format(end_modified_at, "%Y-%m-%d %H:%M:%S", tz = "UTC")
  }
  
  b <- list(page = page, 
            per_page = per_page,
            start_created_at = start_created_at, 
            end_created_at = end_created_at,
            start_modified_at = start_modified_at,
            end_modified_at = end_modified_at,
            sort_order = sort_order, 
            sort_by = sort_by)
  
  nulls <- sapply(b, is.null)
  
  if (all(nulls)) {
    b <- NULL
  } else {
    b <- b[!nulls]
  }  
  
  h <- httr::add_headers(Authorization = token, 'Content-Type' = 'application/json')
  
  
  out <- httr::GET(url = u, config = h, query = b, ...)
  httr::stop_for_status(out)
  parsed_content <- httr::content(out, as = 'parsed')
  
  if (!is.null(parsed_content$data)) {
    lapply(parsed_content$data, `class<-`, "sm_response")
  }
  
  structure(parsed_content, class = 'sm_response_list')
  responses <- parsed_content$data
  
  ##-- Recursively get all responses if all_pages = TRUE
  if (all_pages == TRUE & (!is.null(parsed_content$links[['next']]))) {
    rnext <- get_responses(survey, 
                           collector,
                           bulk,
                           page = page + 1,
                           all_pages,
                           per_page,
                           start_created_at,
                           end_created_at,
                           start_modified_at,
                           end_modified_at,
                           sort_order,
                           sort_by)
    
    responses <- c(responses, rnext)
  }
  
  return (responses)
}