#' @title survey_details
#' 
#' @description Get detailed information about a survey
#' 
#' @param survey A sm_survey object, as retrieved by \code{surveylist()}.
#' @param question_detail A logical value to indicate whether to include details on questions and answer choices.  By default = TRUE.
#' @param oauth_token Your OAuth 2.0 token, as generated by \code{smlogin}. By default, retrieved from \code{getOption('sm_oauth_token')}.
#' 
#' @return A list of objects of class \code{sm_survey}.
#' 
#' @references SurveyMonkey API V3 at \url{https://developer.surveymonkey.com/api/v3/#surveys}
#' 
#' @export 

survey_details <- function(survey,
                           question_details = TRUE,
                           oauth_token = getOption('sm_oauth_token'),
                           ...) {
  if(inherits(survey, 'sm_survey'))
    survey <- survey$id
  if(question_details) {
    u <- paste('https://api.surveymonkey.net/v3/surveys/', survey, '/details?', sep = '')  
  } else {
    u <- paste('https://api.surveymonkey.net/v3/surveys/', survey, '?', sep = '')
  } 
      
  if(!is.null(oauth_token)) {
    token <- paste('bearer', oauth_token)
  } else {
    stop("Must specify 'oauth_token'.  Try using smlogin() first.") 
  }
    
  h <- httr::add_headers(Authorization = token, 'Content-Type' = 'application/json')
  out <- httr::GET(u, config = h, ...)
  httr::stop_for_status(out)
  
  out <- httr::content(out, as = 'parsed')
  out <- structure(out, class = "sm_survey")
  
  return(out)
}
